extraction:
    cpp:
      prepare:
        packages:
          - libcurl4-openssl-dev
          - libboost-all-dev
          - libffi-dev
          - libssl-dev
          - libc6
          - libicu-dev
      after_prepare:
        - git clone https://github.com/zaphoyd/websocketpp.git
        - mkdir build
        - cd build
      configure:
        command:
          cmake .. -G"Unix Makefiles" -DTRAVIS=ON ..


          
      
