language: cpp
compiler: gcc
cache: ccache
matrix:
  include:
  - name: "Stand Alone"
    os: linux
    addons:
        apt:
            sources:
            - ubuntu-toolchain-r-test
            packages:
                - g++-7
    env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo apt-get install libcurl4-openssl-dev
    - sudo apt-get install libboost-all-dev
    - sudo apt-get install libssl-dev
    - sudo apt-get install libc6
    - sudo apt-get install libicu-dev
    - sudo apt-get install valgrind
    - cd ..
    - git clone https://github.com/rathena/rathena.git
    - cd rathena
    - git checkout ab0046cf2c6023ddf2fb54bc4ec2c6886f0098c4
    - cd ../roCORD

install:
    # prepare travis_stand_alone
    - mkdir build
    - cd build
    - cmake -DTRAVIS=ON ..
    - make
    - cd ..
    - chmod u+x install.sh
    - ./install.sh

script:
    - cd build/
    - valgrind --error-exitcode=-1 -q ./roCORD
    - cd ../../

    - cd rathena/build/
    - make install
