language: cpp
compiler: gcc
cache: ccache
matrix:
  include:
  - name: "Stand Alone"
    os: linux
    addons:
        apt:
            sources:
            - ubuntu-toolchain-r-test
            #- sourceline: deb https://dl.bintray.com/solvingj/public-deb unstable main
            packages:
                - g++-7
              #- libcurl4-openssl-dev
              #- libboost-all-dev
              #- libffi-dev
              #- libssl-dev
              #- libicu-dev
              #- libc6
    env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
    - git clone https://github.com/Kitware/CMake.git 
    - sudo apt-get install libcurl4-openssl-dev
    - sudo apt-get install libboost-all-dev
    - sudo apt-get install libffi-dev 
    - sudo apt-get install libssl-dev
    - sudo apt-get install libc6
    - sudo apt-get install libicu-dev
    - pip install --user cget
    - cget install nlohmann/json
    - git clone https://github.com/zaphoyd/websocketpp.git

install:
    - cd CMake
    - ./bootstrap 
    - sudo make
    - sudo make install
    - cd ..
    - mkdir build
    - cd build
    - /usr/local/bin/cmake -DTRAVIS=ON ..
    - make

script:
    - ./roCORD
